### ISSUE TITLE
LearnRust

### ISSUE THREAD

**Issue by woshidama323** [woshidama323/LearnRust#4]
## rust笔记

```shell
### 1. 能否toml中依赖private repo
https://medium.com/@c_ameron/rust-how-to-build-a-docker-image-with-private-cargo-dependencies-ab91c25c4301


```

**Comment by woshidama323** [comment]
cargo run [options] [-- args]
Run a binary or example of the local package.

All the arguments following the two dashes (--) are passed to the binary to run. If you're passing arguments to both Cargo and the binary, the ones after -- go to the binary, the ones before go to Cargo.
--bin name
Run the specified binary.

--example name
Run the specified example.




## 来源： https://doc.rust-lang.org/cargo/commands/cargo-run.html


rust-gdb --args target/debug/benchy merkleproofs --size 2

### 对应cargo的运行方法 https://github.com/filecoin-project/rust-fil-proofs
cargo run --release --bin benchy -- merkleproofs --size 2

### 1. 命令行
https://docs.rs/clap/latest/clap/

### vec
You can explicitly create a Vec with Vec::new:

let v: Vec<i32> = Vec::new();
Run
…or by using the vec! macro:




https_proxy=192.168.20.9:1089 cargo deps -d 4 | dot -Tpng > graph.png
绘制调用关系

**Comment by woshidama323** [comment]
Neptune is a Rust implementation of the Poseidon hash function tuned for Filecoin.
## https://www.poseidon-hash.info/

Poseidon: 
ZK-friendly Hashing
https://eprint.iacr.org/2019/458.pdf Yoshiki


### https://crates.io/crates/bellperson/0.18.2
###bellperson是 bellman的fork版本 在此基础上增加了gpu等并行计算优化

arity 是树的自由度

**Comment by woshidama323** [comment]
### 迁移一个repo 到一个新的地方

```shell
git clone --bare {repo}
cd {project}.git
git push --mirror {new-repo}

## 样例
https_proxy=192.168.20.9:1089 git clone --bare https://github.com/jeek2018/rust-fil-proofs.git


```



[参考资料]
https://gist.github.com/niksumeiko/8972566

**Comment by woshidama323** [comment]
```shell
admindeMac-mini:filecoin-ffi admin$ cat  rust/.cargo/config
[net]
git-fetch-with-cli = true
```

**Comment by woshidama323** [comment]
```shell

### 如果从remote端git 下来依赖包，那么cargo 中不会自动追踪 最新的commit的信息 主要原因是cargo.lock 中已经锁定了主要的依赖版本，需要update 一下才能更新
https_proxy=192.168.20.9:1089 cargo update



```
[参考资料] https://github.com/rust-lang/cargo/issues/8555

**Comment by woshidama323** [comment]
### rust 从git repo中获取到的代码放在这里
$HOME/.cargo/git/checkouts


### 场景，本地测试，开发过程中临时修改代码
https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html

不想push到repo中 可以这么干
```toml
[package]
name = "my-library"
version = "0.1.0"

[dependencies]
uuid = "1.0"

[patch.crates-io]
uuid = { path = "../path/to/uuid" }
```

但是需要注意上面的这个只是针对 需要替换的package 是从crate.io来的时候，可以这样用

```toml
 
 [patch."https://github.com/woshidama323/bellperson"]
bellperson = { version = "0.18.0",path = "/home/fsw/.cargo/git/checkouts/rust-gpu-tools-0b366f849ae22563/ec52b6b/" }

### 如果是从github等其他来源的话，需要这样
```


注意： patch目前不支持 workspace 成员中的Cargo.toml 替换，需要放在根的位置
